"""Emit Python source that reconstructs a typed Pipeline."""

from __future__ import annotations

from datetime import date, datetime, time
from enum import Enum
from typing import Any

from fabric_data_pipelines.activities.base import _ENVELOPE_FIELDS, Activity
from fabric_data_pipelines.activities.control import SwitchCase
from fabric_data_pipelines.activities.raw import RawActivity
from fabric_data_pipelines.pipeline import LibraryVariable, Parameter, Pipeline, Variable
from fabric_data_pipelines.schedule import (
    CronScheduleConfiguration,
    DailyScheduleConfiguration,
    MonthlyScheduleConfiguration,
    Schedule,
    WeeklyScheduleConfiguration,
)
from fabric_data_pipelines.serialization import Expression, FabricModel

# Internal schedule config class names → public aliases exported from the package.
_PUBLIC_CLASS_NAMES: dict[type[Any], str] = {
    CronScheduleConfiguration: "Cron",
    DailyScheduleConfiguration: "Daily",
    WeeklyScheduleConfiguration: "Weekly",
    MonthlyScheduleConfiguration: "Monthly",
}


def _class_name(cls: type[Any]) -> str:
    return _PUBLIC_CLASS_NAMES.get(cls, cls.__name__)


def codegen_pipeline(pipeline: Pipeline) -> str:
    """Generate Python source that rebuilds ``pipeline`` with typed constructors."""
    imports: set[str] = {"Pipeline"}
    body = _emit_pipeline(pipeline, imports)
    import_lines = ",\n    ".join(sorted(imports))
    return (
        '"""Auto-generated by fabric-data-pipelines codegen."""\n'
        "\n"
        f"from fabric_data_pipelines import (\n    {import_lines},\n)\n"
        "\n"
        f"{body}\n"
    )


def _emit_pipeline(pipeline: Pipeline, imports: set[str]) -> str:
    parts: list[str] = [f"name={pipeline.name!r}"]
    if pipeline.description is not None:
        parts.append(f"description={pipeline.description!r}")
    parts.append(f"activities={_emit_list(pipeline.activities, imports)}")
    if pipeline.parameters is not None:
        parts.append(f"parameters={_emit_mapping(pipeline.parameters, imports, Parameter)}")
    if pipeline.variables is not None:
        parts.append(f"variables={_emit_mapping(pipeline.variables, imports, Variable)}")
    if pipeline.library_variables is not None:
        parts.append(
            "library_variables="
            + _emit_mapping(pipeline.library_variables, imports, LibraryVariable)
        )
    if pipeline.concurrency is not None:
        parts.append(f"concurrency={pipeline.concurrency!r}")
    if pipeline.logical_id is not None:
        parts.append(f"logical_id={pipeline.logical_id!r}")
    if pipeline.schedules is not None:
        parts.append(f"schedules={_emit_list(pipeline.schedules, imports)}")
    joined = ",\n    ".join(parts)
    return f"pipeline = Pipeline(\n    {joined},\n)"


def _emit_mapping(
    mapping: dict[str, Any],
    imports: set[str],
    model_cls: type[FabricModel],
) -> str:
    imports.add(model_cls.__name__)
    items: list[str] = []
    for key in mapping:
        value = mapping[key]
        items.append(f"{key!r}: {_emit_value(value, imports)}")
    return "{" + ", ".join(items) + "}"


def _emit_list(values: list[Any], imports: set[str]) -> str:
    if not values:
        return "[]"
    items = ",\n        ".join(_emit_value(v, imports) for v in values)
    return f"[\n        {items},\n    ]"


def _emit_value(value: Any, imports: set[str]) -> str:
    if isinstance(value, Activity):
        return _emit_activity(value, imports)
    if isinstance(value, SwitchCase):
        imports.add("SwitchCase")
        return (
            f"SwitchCase(value={value.value!r}, activities={_emit_list(value.activities, imports)})"
        )
    if isinstance(value, Schedule):
        return _emit_model(value, imports)
    if isinstance(value, Expression):
        imports.add("Expression")
        return f"Expression(value={value.value!r}, type={value.type!r})"
    if isinstance(value, FabricModel):
        return _emit_model(value, imports)
    if isinstance(value, dict):
        items = ", ".join(f"{k!r}: {_emit_value(v, imports)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_emit_value(v, imports) for v in value) + "]"
    if isinstance(value, Enum):
        return repr(value.value)
    if isinstance(value, datetime):
        return repr(value.isoformat())
    if isinstance(value, date):
        return repr(value.isoformat())
    if isinstance(value, time):
        return repr(value.strftime("%H:%M"))
    return repr(value)


def _emit_activity(activity: Activity, imports: set[str]) -> str:
    cls = type(activity)
    name = _class_name(cls)
    imports.add(name)

    if isinstance(activity, RawActivity):
        parts: list[str] = [
            f"name={activity.name!r}",
            f"type={activity.type!r}",
            f"type_properties={_emit_value(activity.type_properties, imports)}",
        ]
        if activity.depends_on:
            parts.append(f"depends_on={_emit_value(activity.depends_on, imports)}")
        if activity.policy is not None:
            parts.append(f"policy={_emit_value(activity.policy, imports)}")
        if activity.external_references is not None:
            parts.append(
                f"external_references={_emit_value(activity.external_references, imports)}"
            )
        if activity.state is not None:
            parts.append(f"state={activity.state!r}")
        if activity.on_inactive_mark_as is not None:
            parts.append(f"on_inactive_mark_as={activity.on_inactive_mark_as!r}")
        if activity.description is not None:
            parts.append(f"description={activity.description!r}")
        if activity.user_properties is not None:
            parts.append(f"user_properties={_emit_value(activity.user_properties, imports)}")
        return f"{name}({', '.join(parts)})"

    parts = [f"name={activity.name!r}"]
    if activity.depends_on:
        parts.append(f"depends_on={_emit_value(activity.depends_on, imports)}")
    if activity.policy is not None:
        parts.append(f"policy={_emit_value(activity.policy, imports)}")
    if activity.external_references is not None:
        parts.append(f"external_references={_emit_value(activity.external_references, imports)}")
    if activity.state is not None:
        parts.append(f"state={activity.state!r}")
    if activity.on_inactive_mark_as is not None:
        parts.append(f"on_inactive_mark_as={activity.on_inactive_mark_as!r}")
    if activity.description is not None:
        parts.append(f"description={activity.description!r}")
    if activity.user_properties is not None:
        parts.append(f"user_properties={_emit_value(activity.user_properties, imports)}")

    exclude = _ENVELOPE_FIELDS | cls._exclude_from_type_properties
    for field_name in cls.model_fields:
        if field_name in exclude:
            continue
        field_value = getattr(activity, field_name)
        if field_value is None:
            continue
        parts.append(f"{field_name}={_emit_value(field_value, imports)}")

    return f"{name}({', '.join(parts)})"


def _emit_model(model: FabricModel, imports: set[str]) -> str:
    cls = type(model)
    name = _class_name(cls)
    imports.add(name)
    parts: list[str] = []
    for field_name, field_info in cls.model_fields.items():
        value = getattr(model, field_name)
        if value is None:
            continue
        # Subclasses like LakehouseTable / SqlMISource set ``type`` in __init__;
        # re-passing the default conflicts with ``super().__init__(type=...)``.
        if field_name == "type" and field_info.default == value:
            continue
        parts.append(f"{field_name}={_emit_value(value, imports)}")
    # Preserve extra="allow" keys (e.g. CopySource storeSettings / formatSettings).
    extras = getattr(model, "__pydantic_extra__", None) or {}
    for key, value in extras.items():
        if value is None:
            continue
        parts.append(f"{key}={_emit_value(value, imports)}")
    return f"{name}({', '.join(parts)})"
